import type { ListeningSection, Speaker } from '@/types/content'

const narrator: Speaker = { name: 'Narrator', voice: 'bm_fable' }

export const listening: ListeningSection = {
  reviewSeconds: 120,
  parts: [
    // ─── Part 1 ─────────────────────────────────────────────────────────────
    {
      id: 'l1',
      intro: 'Questions 1–10',
      context: 'A telephone conversation between a leisure centre receptionist and a woman who wants to join.',
      speakers: {
        N: narrator,
        D: { name: 'Daniel', voice: 'bm_george' },
        S: { name: 'Sophie', voice: 'bf_emma' },
      },
      script: [
        {
          type: 'narrator',
          text: 'Part 1. You will hear a telephone conversation between a receptionist at a leisure centre and a woman who is interested in becoming a member. First, you have some time to look at questions 1 to 5.',
        },
        { type: 'pause', seconds: 30 },
        { type: 'narrator', text: 'Now listen carefully and answer questions 1 to 5.' },
        { type: 'pause', seconds: 1 },
        { type: 'line', speaker: 'D', text: 'Good morning, Riverside Leisure Centre, Daniel speaking. How can I help?' },
        {
          type: 'line',
          speaker: 'S',
          text: "Oh, hi. I've just moved to the area and I'm thinking of joining the centre. I was hoping you could tell me a bit about the memberships.",
        },
        {
          type: 'line',
          speaker: 'D',
          text: "Of course. I'll just take a few details first, if that's all right, and then I'll run through the options. Could I have your name?",
        },
        { type: 'line', speaker: 'S', text: "Yes, it's Sophie Denholm." },
        { type: 'line', speaker: 'D', text: 'And how do you spell your surname?' },
        { type: 'line', speaker: 'S', text: "It's D-E-N-H-O-L-M.", say: "It's D, E, N, H, O, L, M." },
        { type: 'line', speaker: 'D', text: "Thanks. And what's your address, Sophie?" },
        { type: 'line', speaker: 'S', text: "It's 27 Kingsley Road.", say: "It's twenty-seven Kingsley Road." },
        { type: 'line', speaker: 'D', text: 'Is that K-I-N-G-S-L-E-Y?', say: 'Is that K, I, N, G, S, L, E, Y?' },
        { type: 'line', speaker: 'S', text: "That's right. It's the road that runs behind the railway station." },
        { type: 'line', speaker: 'D', text: 'Oh yes, I know it. And could I take a contact number?' },
        {
          type: 'line',
          speaker: 'S',
          text: 'Sure. My mobile is 07946 218530.',
          say: 'Sure. My mobile is oh seven nine four six, two one eight, five three oh.',
        },
        {
          type: 'line',
          speaker: 'D',
          text: 'Let me read that back to you: 07946 218530.',
          say: 'Let me read that back to you. Oh seven nine four six, two one eight, five three oh.',
        },
        { type: 'line', speaker: 'S', text: "That's it." },
        {
          type: 'line',
          speaker: 'D',
          text: 'Great. Can I ask how you heard about the centre? We like to keep track of which advertising works.',
        },
        {
          type: 'line',
          speaker: 'S',
          text: "I think I saw something in the local paper… no, actually, it was a poster. There's one up in the library, near the entrance.",
          say: "I think I saw something in the local paper. No, actually, it was a poster. There's one up in the library, near the entrance.",
        },
        {
          type: 'line',
          speaker: 'D',
          text: "The library, lovely. Right, so let me tell you about the memberships. The one most people go for is our Standard membership.",
        },
        { type: 'line', speaker: 'S', text: 'And how much is that?' },
        {
          type: 'line',
          speaker: 'D',
          text: "It's £32 a month. It used to be £35, but we brought the price down in January.",
          say: "It's thirty-two pounds a month. It used to be thirty-five, but we brought the price down in January.",
        },
        { type: 'line', speaker: 'S', text: "Oh, that's not bad at all." },
        { type: 'pause', seconds: 2 },
        {
          type: 'narrator',
          text: 'Before you hear the rest of the conversation, you have some time to look at questions 6 to 10.',
        },
        { type: 'pause', seconds: 30 },
        { type: 'narrator', text: 'Now listen and answer questions 6 to 10.' },
        { type: 'pause', seconds: 1 },
        {
          type: 'line',
          speaker: 'D',
          text: 'So, with Standard membership you can use the gym and the swimming pool whenever the centre is open, and you also get a free fitness assessment with one of our trainers when you join.',
        },
        { type: 'line', speaker: 'S', text: 'What does that involve?' },
        {
          type: 'line',
          speaker: 'D',
          text: "They'll check things like your heart rate and flexibility, and then put together a personal programme for you.",
        },
        { type: 'line', speaker: 'S', text: 'Sounds useful. Are there any cheaper options?' },
        {
          type: 'line',
          speaker: 'D',
          text: "There's Off-peak membership, which is £21 a month. You can come in any time from Monday to Friday until five o'clock, but it doesn't cover weekends.",
          say: "There's off-peak membership, which is twenty-one pounds a month. You can come in any time from Monday to Friday until five o'clock, but it doesn't cover weekends.",
        },
        {
          type: 'line',
          speaker: 'S',
          text: "Hmm. I work during the day, so I'd mostly be coming in the evenings anyway. What about families? My partner might want to join too, and we have a little boy.",
        },
        {
          type: 'line',
          speaker: 'D',
          text: "Then you might be interested in Family membership. That's £58 a month for two adults and up to three children, and the children get free swimming lessons on Saturday mornings.",
          say: "Then you might be interested in family membership. That's fifty-eight pounds a month for two adults and up to three children, and the children get free swimming lessons on Saturday mornings.",
        },
        { type: 'line', speaker: 'S', text: "Oh, that could be good. He's six and he can't swim yet." },
        {
          type: 'line',
          speaker: 'D',
          text: "Well, it's a great age to start. And there's one more thing: normally there's a joining fee of £25, but at the moment we're waiving it for anyone who signs up before the end of June.",
          say: "Well, it's a great age to start. And there's one more thing. Normally there's a joining fee of twenty-five pounds, but at the moment we're waiving it for anyone who signs up before the end of June.",
        },
        { type: 'line', speaker: 'S', text: 'The end of June? I thought the poster said the offer finished in May.' },
        {
          type: 'line',
          speaker: 'D',
          text: "It was supposed to, but it's been so popular that the manager decided to extend it.",
        },
        { type: 'line', speaker: 'S', text: 'Great. And if I do join, what happens next?' },
        {
          type: 'line',
          speaker: 'D',
          text: "You'd book an induction session, where one of our staff shows you how to use the equipment safely. Just wear something comfortable. We provide towels, so there's no need to bring one, but you will need a padlock for the lockers in the changing rooms.",
        },
        { type: 'line', speaker: 'S', text: "A padlock. OK, I'll remember that." },
        { type: 'line', speaker: 'D', text: 'Is there anything else I can help you with?' },
        {
          type: 'line',
          speaker: 'S',
          text: "No, that's everything, thanks. I'll talk to my partner and probably call back tomorrow.",
        },
        { type: 'line', speaker: 'D', text: 'No problem. Thanks for calling, Sophie.' },
        { type: 'pause', seconds: 2 },
        { type: 'narrator', text: 'That is the end of Part 1. You now have half a minute to check your answers to Part 1.' },
        { type: 'pause', seconds: 30 },
      ],
      groups: [
        {
          id: 'l1-g1',
          type: 'gap',
          layout: 'notes',
          from: 1,
          to: 10,
          title: 'Riverside Leisure Centre — membership enquiry',
          wordLimit: { words: 1, number: true },
          instructions: ['Complete the notes below.', 'Write **ONE WORD AND/OR A NUMBER** for each answer.'],
          lines: [
            '# Caller details',
            '- Name: Sophie {{1}}',
            '- Address: 27 {{2}} Road',
            '- Mobile number: {{3}}',
            '- Heard about the centre from a poster in the {{4}}',
            '# Membership options',
            '- **Standard:** £{{5}} per month',
            '-- use of gym and pool at any time',
            '-- a free fitness {{6}} when you join',
            '- **Off-peak:** £21 per month',
            '-- cannot be used at {{7}}',
            '- **Family:** £58 per month',
            '-- children get free {{8}} lessons',
            '# Other information',
            '- no joining fee until the end of {{9}}',
            '- bring a {{10}} to the induction session',
          ],
        },
      ],
    },

    // ─── Part 2 ─────────────────────────────────────────────────────────────
    {
      id: 'l2',
      intro: 'Questions 11–20',
      context: 'A volunteer coordinator welcomes new volunteers to a country park.',
      speakers: {
        N: narrator,
        C: { name: 'Claire', voice: 'bf_isabella' },
      },
      script: [
        {
          type: 'narrator',
          text: 'Part 2. You will hear a volunteer coordinator talking to a group of new volunteers at a country park. First, you have some time to look at questions 11 to 14.',
        },
        { type: 'pause', seconds: 30 },
        { type: 'narrator', text: 'Now listen carefully and answer questions 11 to 14.' },
        { type: 'pause', seconds: 1 },
        {
          type: 'line',
          speaker: 'C',
          text: "Good morning, everyone, and welcome to Thornbury Country Park. My name's Claire Hughes, and I coordinate the volunteer programme here. Thank you all for giving up your time to help us this summer. I'll start with a little background, then go through what you'll be doing, and after that I'll show you where everything is on the map.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "A lot of visitors assume that the park has always been open countryside, or that it was once farmland, and it's true that there were a few small farms around the edges. But in fact, for nearly three hundred years, this whole area formed part of a large private estate belonging to the Thornbury family. The house itself was destroyed by fire in 1921, and the council bought the land in the 1950s and opened it to the public.",
          say: "A lot of visitors assume that the park has always been open countryside, or that it was once farmland, and it's true that there were a few small farms around the edges. But in fact, for nearly three hundred years, this whole area formed part of a large private estate belonging to the Thornbury family. The house itself was destroyed by fire in nineteen twenty-one, and the council bought the land in the nineteen fifties and opened it to the public.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "Now, what will you actually be doing? I know some of you are keen to lead guided walks, and you'll certainly get the chance to do that later in the summer, once you know the park well. The footpaths are maintained by our team of rangers, so you won't be involved in that. For your first month, we'd like all of you to be based at the visitor centre, answering questions, handing out maps and helping with school groups.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "A few practical points. We'll give each of you a green jacket, and please make sure you wear it whenever you're on duty, so that visitors can recognise you. You don't need any special footwear; trainers are fine in summer. We used to ask volunteers to wear name badges, but a lot of people forgot them, so these days they're optional.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "You may also have noticed that the car park has moved. Some people think this was done to reduce traffic on the main road, but that's never really been a problem here. What happened was that a survey showed that the roots of the old oak trees beside the original car park were being damaged by cars parking over them, so we've moved it to protect the trees. The old car park will be planted with grass.",
        },
        { type: 'pause', seconds: 2 },
        {
          type: 'narrator',
          text: 'Before you hear the rest of the talk, you have some time to look at questions 15 to 20.',
        },
        { type: 'pause', seconds: 30 },
        { type: 'narrator', text: 'Now listen and answer questions 15 to 20.' },
        { type: 'pause', seconds: 1 },
        {
          type: 'line',
          speaker: 'C',
          text: "Right, if you look at your maps, you'll see that we're standing at the main entrance, at the bottom of the map. The main path runs straight ahead of us, northwards, all the way up to the woodland. The visitor centre is the building just on our right, and the car park is over on the left.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "Let's start with the café. Until last year it was inside the visitor centre, but it's now got its own building, which is just across the main path from the visitor centre, on the left as you walk in. So it's the first building you pass.",
          say: "Let's start with the cafe. Until last year it was inside the visitor centre, but it's now got its own building, which is just across the main path from the visitor centre, on the left as you walk in. So it's the first building you pass.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "Now, if you follow the main path north, you'll see the lake on your left. Keep going until you reach the bridge over the stream. Just before the bridge, there's a path going off to the left, which takes you along the top of the lake. The bird hide is on that path, on the northern shore of the lake, looking south over the water. It's a great place to see herons in the early morning.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "Families always ask about the adventure playground. We wanted it as far from the lake as possible, for safety reasons, so it's right over on the eastern side of the park, behind the visitor centre. If you walk round the right-hand side of the visitor centre and keep going east, you can't miss it.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: 'The picnic area is a very popular spot. To get there, cross the bridge, then take the first path on the right. The picnic area is just along there, on the right-hand side of the path, beside the stream.',
        },
        {
          type: 'line',
          speaker: 'C',
          text: "On the western side of the lake, the side furthest from the main path, there's a wildflower meadow. It's at its best in June and July, and we ask visitors to stay on the paths there so they don't damage the plants.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "And finally, the tree nursery, where we grow young trees for planting around the park. That's in the woodland at the very top of the map, in the north-west corner. It isn't open to the public, but volunteers will be helping there in the autumn.",
        },
        {
          type: 'line',
          speaker: 'C',
          text: "Right, let's go over to the visitor centre and I'll introduce you to the rest of the team.",
        },
        { type: 'pause', seconds: 2 },
        { type: 'narrator', text: 'That is the end of Part 2. You now have half a minute to check your answers to Part 2.' },
        { type: 'pause', seconds: 30 },
      ],
      groups: [
        {
          id: 'l2-g1',
          type: 'mcq',
          from: 11,
          to: 14,
          instructions: ['Choose the correct letter, **A**, **B** or **C**.'],
          questions: [
            {
              n: 11,
              text: 'Before it became a park, the land was mainly',
              options: [
                { key: 'A', text: 'farmland.' },
                { key: 'B', text: 'a private estate.' },
                { key: 'C', text: 'open countryside.' },
              ],
            },
            {
              n: 12,
              text: 'During their first month, the volunteers will',
              options: [
                { key: 'A', text: 'lead guided walks.' },
                { key: 'B', text: 'repair footpaths.' },
                { key: 'C', text: 'work at the visitor centre.' },
              ],
            },
            {
              n: 13,
              text: 'When they are on duty, volunteers must wear',
              options: [
                { key: 'A', text: 'a green jacket.' },
                { key: 'B', text: 'special boots.' },
                { key: 'C', text: 'a name badge.' },
              ],
            },
            {
              n: 14,
              text: 'Why was the car park moved?',
              options: [
                { key: 'A', text: 'to reduce traffic on the main road' },
                { key: 'B', text: 'to protect some old trees' },
                { key: 'C', text: 'to create more parking spaces' },
              ],
            },
          ],
        },
        {
          id: 'l2-g2',
          type: 'map',
          from: 15,
          to: 20,
          visual: 'thornbury-park',
          letters: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
          instructions: ['Label the map below.', 'Choose the correct letter, **A–H**, next to Questions 15–20.'],
          questions: [
            { n: 15, text: 'Café' },
            { n: 16, text: 'Bird hide' },
            { n: 17, text: 'Adventure playground' },
            { n: 18, text: 'Picnic area' },
            { n: 19, text: 'Wildflower meadow' },
            { n: 20, text: 'Tree nursery' },
          ],
        },
      ],
    },

    // ─── Part 3 ─────────────────────────────────────────────────────────────
    {
      id: 'l3',
      intro: 'Questions 21–30',
      context: 'Two students, Maya and Leo, discuss their research project on food waste.',
      speakers: {
        N: narrator,
        M: { name: 'Maya', voice: 'af_bella' },
        L: { name: 'Leo', voice: 'bm_george' },
      },
      script: [
        {
          type: 'narrator',
          text: 'Part 3. You will hear two students, Maya and Leo, discussing a research project on food waste. First, you have some time to look at questions 21 to 26.',
        },
        { type: 'pause', seconds: 30 },
        { type: 'narrator', text: 'Now listen carefully and answer questions 21 to 26.' },
        { type: 'pause', seconds: 1 },
        {
          type: 'line',
          speaker: 'L',
          text: 'So, Maya, shall we go through the plan for the food waste project before we see Dr Patel on Thursday?',
          say: 'So, Maya, shall we go through the plan for the food waste project before we see Doctor Patel on Thursday?',
        },
        {
          type: 'line',
          speaker: 'M',
          text: "Good idea. I was just thinking about how we'd explain why we chose the topic. She's bound to ask.",
        },
        {
          type: 'line',
          speaker: 'L',
          text: "Well, it wasn't her suggestion, that's for sure. She gave us that long list of topics, and food waste wasn't even on it.",
        },
        {
          type: 'line',
          speaker: 'M',
          text: "No. And when we started I was worried there wouldn't be much research to draw on, and I was right — there's very little on university canteens. I think the real reason was just that we'd both noticed how much food gets thrown away in the cafeteria here. Every lunchtime, the bins are full.",
          say: "No. And when we started I was worried there wouldn't be much research to draw on, and I was right. There's very little on university canteens. I think the real reason was just that we'd both noticed how much food gets thrown away in the cafeteria here. Every lunchtime, the bins are full.",
        },
        { type: 'line', speaker: 'L', text: "Exactly. It seemed like a real problem on our own doorstep. Let's say that." },
        { type: 'line', speaker: 'M', text: 'OK. Then there\'s the pilot survey. Did anything in the results surprise you?' },
        {
          type: 'line',
          speaker: 'L',
          text: "Well, I expected quite a few people wouldn't bother filling it in, but we actually got a good response — over two hundred students.",
          say: "Well, I expected quite a few people wouldn't bother filling it in, but we actually got a good response. Over two hundred students.",
        },
        {
          type: 'line',
          speaker: 'M',
          text: "Yes, that was great. And I wasn't surprised that lots of people said they skip breakfast — that's just student life. But I hadn't expected bread to come out on top as the most wasted item. I'd assumed it would be vegetables.",
          say: "Yes, that was great. And I wasn't surprised that lots of people said they skip breakfast. That's just student life. But I hadn't expected bread to come out on top as the most wasted item. I'd assumed it would be vegetables.",
        },
        {
          type: 'line',
          speaker: 'L',
          text: "Me too. It's because the bread rolls come free with every meal, so people take one whether they want it or not.",
        },
        {
          type: 'line',
          speaker: 'M',
          text: 'That makes sense. Now, the main part of our research is weighing the waste. How often should we do that?',
        },
        {
          type: 'line',
          speaker: 'L',
          text: 'I was thinking every day for a month, but that might be too ambitious, with our other assignments.',
        },
        {
          type: 'line',
          speaker: 'M',
          text: "Let's see what Dr Patel says. But whatever we decide, we can't do it without the kitchen staff. They're the ones who scrape the plates, so they'll have to put the food waste into separate bins for us.",
          say: "Let's see what Doctor Patel says. But whatever we decide, we can't do it without the kitchen staff. They're the ones who scrape the plates, so they'll have to put the food waste into separate bins for us.",
        },
        {
          type: 'line',
          speaker: 'L',
          text: "Yes, we definitely need them on our side. I'll speak to the catering manager this week.",
        },
        { type: 'line', speaker: 'M', text: 'Great. And then there are the interviews.' },
        {
          type: 'line',
          speaker: 'L',
          text: "I thought we could film them, but then I realised people might not be very relaxed in front of a camera.",
        },
        {
          type: 'line',
          speaker: 'M',
          text: "An audio recording on my phone should be fine. And I don't think we should do them in the cafeteria, because it's far too noisy. We could use one of the seminar rooms.",
        },
        {
          type: 'line',
          speaker: 'L',
          text: "Fair enough. The most important thing, though, is that they don't take up too much of people's time. If we say it'll only take five minutes, we'll get far more volunteers.",
        },
        { type: 'line', speaker: 'M', text: 'Agreed. Five minutes, no more.' },
        {
          type: 'line',
          speaker: 'L',
          text: "We also need to decide what changes we're going to recommend to the cafeteria at the end of the project.",
        },
        {
          type: 'line',
          speaker: 'M',
          text: 'Well, one thing that has worked at other universities is getting rid of trays. Apparently people take less food if they can only carry a plate.',
        },
        {
          type: 'line',
          speaker: 'L',
          text: "I read about that too, but the catering manager told me they tried it a few years ago and there were too many accidents with people carrying hot drinks. So I don't think we should suggest that.",
        },
        { type: 'line', speaker: 'M', text: 'Fair enough. What about composting?' },
        {
          type: 'line',
          speaker: 'L',
          text: "They already send all their food waste to be composted, so that wouldn't be anything new.",
        },
        {
          type: 'line',
          speaker: 'M',
          text: 'Right. I think the most obvious change is offering smaller portions for a lower price. A lot of people in the survey said the portions were too big.',
        },
        {
          type: 'line',
          speaker: 'L',
          text: 'Definitely, we should recommend that. And I like the idea of putting up a display showing how much food was wasted each week. If people can see the figures, they might think twice.',
        },
        { type: 'line', speaker: 'M', text: "Yes, let's include that too. What about banning takeaway boxes?" },
        {
          type: 'line',
          speaker: 'L',
          text: "I don't think that's really about food waste. It's more about packaging.",
        },
        { type: 'line', speaker: 'M', text: 'True. So those are our two.' },
        { type: 'pause', seconds: 2 },
        {
          type: 'narrator',
          text: 'Before you hear the rest of the discussion, you have some time to look at questions 27 to 30.',
        },
        { type: 'pause', seconds: 30 },
        { type: 'narrator', text: 'Now listen and answer questions 27 to 30.' },
        { type: 'pause', seconds: 1 },
        {
          type: 'line',
          speaker: 'M',
          text: 'Now, Dr Patel wants us to comment on our sources in the literature review. What did you think of the online article?',
          say: 'Now, Doctor Patel wants us to comment on our sources in the literature review. What did you think of the online article?',
        },
        {
          type: 'line',
          speaker: 'L',
          text: "The one about the university in California? It was quite short, but that's actually where we got the idea of weighing the waste every day, so I think it's worth including.",
        },
        { type: 'line', speaker: 'M', text: 'Yes, definitely. And the government report?' },
        {
          type: 'line',
          speaker: 'L',
          text: "It's very long, and I'm not sure we need most of it. But it's got some really useful figures on how much food is wasted in the country each year, and we can use those in our introduction.",
        },
        { type: 'line', speaker: 'M', text: 'OK. What about the documentary we watched?' },
        {
          type: 'line',
          speaker: 'L',
          text: "I enjoyed it, but it was about food waste in general — farms and supermarkets and so on. There was nothing specific about universities or even restaurants, so I'm not sure how much we can use from it.",
          say: "I enjoyed it, but it was about food waste in general. Farms and supermarkets and so on. There was nothing specific about universities or even restaurants, so I'm not sure how much we can use from it.",
        },
        { type: 'line', speaker: 'M', text: 'I agree. And finally, that chapter in the environmental science textbook.' },
        {
          type: 'line',
          speaker: 'L',
          text: "The problem with that is it was written in the 1990s. So much has changed since then, especially with all the new recycling schemes. I think we should only mention it briefly.",
          say: "The problem with that is it was written in the nineteen nineties. So much has changed since then, especially with all the new recycling schemes. I think we should only mention it briefly.",
        },
        { type: 'line', speaker: 'M', text: "Fair enough. Right, I think we're ready for Thursday." },
        { type: 'pause', seconds: 2 },
        { type: 'narrator', text: 'That is the end of Part 3. You now have half a minute to check your answers to Part 3.' },
        { type: 'pause', seconds: 30 },
      ],
      groups: [
        {
          id: 'l3-g1',
          type: 'mcq',
          from: 21,
          to: 24,
          instructions: ['Choose the correct letter, **A**, **B** or **C**.'],
          questions: [
            {
              n: 21,
              text: 'Why did the students choose food waste as their topic?',
              options: [
                { key: 'A', text: 'Their tutor suggested it.' },
                { key: 'B', text: 'There was a lot of previous research on it.' },
                { key: 'C', text: 'They had noticed a problem at their university.' },
              ],
            },
            {
              n: 22,
              text: 'What surprised the students about the results of the pilot survey?',
              options: [
                { key: 'A', text: 'the number of students who completed it' },
                { key: 'B', text: 'how many students skip breakfast' },
                { key: 'C', text: 'the type of food that was wasted most' },
              ],
            },
            {
              n: 23,
              text: 'The students agree that weighing the waste will require',
              options: [
                { key: 'A', text: 'help from the kitchen staff.' },
                { key: 'B', text: 'a whole month of work.' },
                { key: 'C', text: 'special equipment.' },
              ],
            },
            {
              n: 24,
              text: 'The students decide that the interviews will',
              options: [
                { key: 'A', text: 'be recorded on video.' },
                { key: 'B', text: 'take place in the cafeteria.' },
                { key: 'C', text: 'be kept short.' },
              ],
            },
          ],
        },
        {
          id: 'l3-g2',
          type: 'mcq-multi',
          from: 25,
          to: 26,
          instructions: ['Choose **TWO** letters, **A–E**.'],
          stem: 'Which **TWO** changes will the students recommend to the cafeteria?',
          options: [
            { key: 'A', text: 'removing trays' },
            { key: 'B', text: 'starting a composting scheme' },
            { key: 'C', text: 'offering smaller portions at a lower price' },
            { key: 'D', text: 'displaying weekly waste figures' },
            { key: 'E', text: 'banning takeaway boxes' },
          ],
        },
        {
          id: 'l3-g3',
          type: 'matching',
          display: 'select',
          from: 27,
          to: 30,
          instructions: [
            'What comment does Leo make about each of the following sources?',
            'Choose **FOUR** answers from the box and write the correct letter, **A–F**, next to Questions 27–30.',
          ],
          optionsTitle: 'Comments',
          options: [
            { key: 'A', text: 'It was out of date.' },
            { key: 'B', text: 'It contained useful statistics.' },
            { key: 'C', text: 'It was too general.' },
            { key: 'D', text: 'It gave them an idea for their method.' },
            { key: 'E', text: 'It was difficult to understand.' },
            { key: 'F', text: 'It was written by a well-known expert.' },
          ],
          questions: [
            { n: 27, text: 'the online article' },
            { n: 28, text: 'the government report' },
            { n: 29, text: 'the documentary' },
            { n: 30, text: 'the textbook chapter' },
          ],
        },
      ],
    },

    // ─── Part 4 ─────────────────────────────────────────────────────────────
    {
      id: 'l4',
      intro: 'Questions 31–40',
      context: 'A lecture on the kakapo, a rare parrot from New Zealand, and the effort to save it.',
      speakers: {
        N: narrator,
        T: { name: 'Lecturer', voice: 'af_heart' },
      },
      script: [
        {
          type: 'narrator',
          text: 'Part 4. You will hear a lecture about a rare bird from New Zealand. First, you have some time to look at questions 31 to 40.',
        },
        { type: 'pause', seconds: 45 },
        { type: 'narrator', text: 'Now listen carefully and answer questions 31 to 40.' },
        { type: 'pause', seconds: 1 },
        {
          type: 'line',
          speaker: 'T',
          text: "Good afternoon. In today's lecture in our series on conservation biology, I'm going to talk about one of the most unusual birds in the world, the kakapo of New Zealand, and about the extraordinary efforts that have been made to save it from extinction.",
        },
        {
          type: 'line',
          speaker: 'T',
          text: "The kakapo is a parrot, but a very strange one. It's the heaviest parrot in the world — a male can weigh up to four kilograms — and it's the only parrot that cannot fly. It does have wings, but it uses them mainly for balance, and to break its fall when it jumps down from trees. Kakapo are also nocturnal, which means they're active at night, and they spend the day hidden among the vegetation. In fact, their name comes from the Māori language and means 'night parrot'.",
          say: "The kakapo is a parrot, but a very strange one. It's the heaviest parrot in the world. A male can weigh up to four kilograms. And it's the only parrot that cannot fly. It does have wings, but it uses them mainly for balance, and to break its fall when it jumps down from trees. Kakapo are also nocturnal, which means they're active at night, and they spend the day hidden among the vegetation. In fact, their name comes from the Maori language and means night parrot.",
        },
        {
          type: 'line',
          speaker: 'T',
          text: 'One feature that sets the kakapo apart from most other birds is its sense of smell. Most birds rely almost entirely on sight, but the kakapo has a very well-developed sense of smell, which it uses to find food in the dark. Researchers have also found that each kakapo has its own distinctive scent, which may help the birds to recognise each other.',
        },
        {
          type: 'line',
          speaker: 'T',
          text: "Kakapo are also exceptionally long-lived. Some are thought to reach sixty years or more, and because there are so few of them, every bird has a name and is known individually to the rangers who look after them.",
        },
        {
          type: 'line',
          speaker: 'T',
          text: "The kakapo's breeding behaviour is unusual too. In the breeding season, the males gather on the tops of hills and dig shallow bowls in the ground. They sit in these bowls and produce a deep booming sound, rather like a foghorn, which can be heard several kilometres away. The females travel to the area, listen to the males and choose a mate. But this only happens in certain years. Kakapo breed only when the rimu, a native tree, produces a large quantity of fruit, which happens roughly every two to four years. The fruit is rich in vitamin D and calcium, which the chicks need in order to grow.",
          say: "The kakapo's breeding behaviour is unusual too. In the breeding season, the males gather on the tops of hills and dig shallow bowls in the ground. They sit in these bowls and produce a deep booming sound, rather like a foghorn, which can be heard several kilometres away. The females travel to the area, listen to the males and choose a mate. But this only happens in certain years. Kakapo breed only when the rimu, a native tree, produces a large quantity of fruit, which happens roughly every two to four years. The fruit is rich in vitamin D and calcium, which the chicks need in order to grow.",
        },
        {
          type: 'line',
          speaker: 'T',
          text: "So why did the kakapo become so rare? Before humans arrived, New Zealand had no land mammals apart from bats, so the kakapo had no reason to fear predators on the ground. When it was threatened, its main defence was simply to freeze and rely on its green feathers for camouflage. That worked well against birds of prey, which hunt by sight, but it was useless against mammals, which hunt by smell. Early settlers hunted the kakapo for food, and later, introduced mammals such as stoats, cats and rats killed huge numbers of birds, eggs and chicks. By 1995, only fifty-one kakapo were known to survive.",
          say: "So why did the kakapo become so rare? Before humans arrived, New Zealand had no land mammals apart from bats, so the kakapo had no reason to fear predators on the ground. When it was threatened, its main defence was simply to freeze and rely on its green feathers for camouflage. That worked well against birds of prey, which hunt by sight, but it was useless against mammals, which hunt by smell. Early settlers hunted the kakapo for food, and later, introduced mammals such as stoats, cats and rats killed huge numbers of birds, eggs and chicks. By nineteen ninety-five, only fifty-one kakapo were known to survive.",
        },
        {
          type: 'line',
          speaker: 'T',
          text: "So what has been done? The most important step was to move every surviving bird to small offshore islands where predators have been removed. Without that, the species would almost certainly have disappeared. Each bird is fitted with a small radio transmitter, so that rangers can check its location and activity, and every nest is watched closely during the breeding season. When the rimu trees produce fruit, rangers also put out extra food for the females, which helps them to raise more chicks.",
          say: "So what has been done? The most important step was to move every surviving bird to small offshore islands where predators have been removed. Without that, the species would almost certainly have disappeared. Each bird is fitted with a small radio transmitter, so that rangers can check its location and activity, and every nest is watched closely during the breeding season. When the rimu trees produce fruit, rangers also put out extra food for the females, which helps them to raise more chicks.",
        },
        {
          type: 'line',
          speaker: 'T',
          text: 'More recently, technology has played a growing role. Because so few birds survive, there is a serious risk of inbreeding, so scientists have sequenced the genome of every living kakapo. This means they can choose which birds should breed, in order to keep as much genetic diversity as possible in the population.',
        },
        {
          type: 'line',
          speaker: 'T',
          text: "These efforts have been remarkably successful. The population has now grown to more than two hundred birds, although the kakapo is still classified as critically endangered. And the programme has taught conservationists a great deal that can be applied to other rare species — which is what we'll look at next week.",
          say: "These efforts have been remarkably successful. The population has now grown to more than two hundred birds, although the kakapo is still classified as critically endangered. And the programme has taught conservationists a great deal that can be applied to other rare species, which is what we'll look at next week.",
        },
        { type: 'pause', seconds: 2 },
        { type: 'narrator', text: 'That is the end of Part 4. You now have half a minute to check your answers to Part 4.' },
        { type: 'pause', seconds: 30 },
        { type: 'narrator', text: 'That is the end of the listening test.' },
      ],
      groups: [
        {
          id: 'l4-g1',
          type: 'gap',
          layout: 'notes',
          from: 31,
          to: 40,
          title: 'The kakapo',
          wordLimit: { words: 1 },
          instructions: ['Complete the notes below.', 'Write **ONE WORD ONLY** for each answer.'],
          lines: [
            '# Description',
            "- the world's heaviest parrot, and the only one unable to {{31}}",
            '- active at {{32}}',
            '- has a good sense of {{33}}, which is unusual in birds',
            '- each bird has its own distinctive {{34}}',
            '# Breeding',
            '- males produce a deep {{35}} sound from bowls dug on hilltops',
            '- only breeds when rimu trees produce a large amount of {{36}}',
            '# Reasons for decline',
            '- when threatened, it freezes and relies on {{37}}',
            '- killed by introduced mammals such as {{38}}, cats and rats',
            '# Conservation',
            '- all birds moved to offshore {{39}} without predators',
            '- scientists have sequenced the {{40}} of every living bird',
          ],
        },
      ],
    },
  ],

  answers: {
    1: { accept: ['Denholm'], evidence: "It's D-E-N-H-O-L-M." },
    2: { accept: ['Kingsley'], evidence: 'Is that K-I-N-G-S-L-E-Y?' },
    3: { accept: ['07946218530', '07946 218530'], evidence: 'My mobile is 07946 218530.' },
    4: {
      accept: ['library'],
      evidence: "There's one up in the library, near the entrance.",
      explanation: 'She first mentions the local paper, then corrects herself.',
    },
    5: {
      accept: ['32', 'thirty-two', '32.00'],
      evidence: "It's £32 a month.",
      explanation: '£35 was the old price.',
    },
    6: { accept: ['assessment'], evidence: 'you also get a free fitness assessment' },
    7: { accept: ['weekends', 'weekend'], evidence: "but it doesn't cover weekends" },
    8: { accept: ['swimming'], evidence: 'the children get free swimming lessons on Saturday mornings' },
    9: {
      accept: ['June'],
      evidence: 'anyone who signs up before the end of June',
      explanation: 'The offer was due to finish in May but has been extended.',
    },
    10: {
      accept: ['padlock'],
      evidence: 'you will need a padlock for the lockers',
      explanation: 'Towels are provided, so a towel is not needed.',
    },
    11: {
      accept: ['B'],
      evidence: 'this whole area formed part of a large private estate',
      explanation: 'There were only "a few small farms around the edges".',
    },
    12: { accept: ['C'], evidence: "we'd like all of you to be based at the visitor centre" },
    13: {
      accept: ['A'],
      evidence: "please make sure you wear it whenever you're on duty",
      explanation: 'Special footwear is not needed and name badges are optional.',
    },
    14: { accept: ['B'], evidence: "so we've moved it to protect the trees" },
    15: { accept: ['C'], evidence: 'just across the main path from the visitor centre, on the left as you walk in' },
    16: { accept: ['A'], evidence: 'on the northern shore of the lake, looking south over the water' },
    17: { accept: ['G'], evidence: "it's right over on the eastern side of the park, behind the visitor centre" },
    18: { accept: ['E'], evidence: 'cross the bridge, then take the first path on the right' },
    19: { accept: ['B'], evidence: "On the western side of the lake, the side furthest from the main path, there's a wildflower meadow." },
    20: { accept: ['H'], evidence: 'in the woodland at the very top of the map, in the north-west corner' },
    21: {
      accept: ['C'],
      evidence: "we'd both noticed how much food gets thrown away in the cafeteria here",
      explanation: 'The tutor did not suggest it, and there was little previous research.',
    },
    22: {
      accept: ['C'],
      evidence: "But I hadn't expected bread to come out on top as the most wasted item.",
    },
    23: { accept: ['A'], evidence: "we can't do it without the kitchen staff" },
    24: { accept: ['C'], evidence: "If we say it'll only take five minutes, we'll get far more volunteers." },
    25: {
      accept: ['C'],
      evidence: 'offering smaller portions for a lower price',
      explanation: 'Trays were rejected (accidents), composting already happens, and takeaway boxes are about packaging.',
    },
    26: {
      accept: ['D'],
      evidence: 'putting up a display showing how much food was wasted each week',
      explanation: 'Trays were rejected (accidents), composting already happens, and takeaway boxes are about packaging.',
    },
    27: { accept: ['D'], evidence: "that's actually where we got the idea of weighing the waste every day" },
    28: { accept: ['B'], evidence: "it's got some really useful figures" },
    29: { accept: ['C'], evidence: 'it was about food waste in general' },
    30: { accept: ['A'], evidence: 'it was written in the 1990s' },
    31: { accept: ['fly'], evidence: "it's the only parrot that cannot fly" },
    32: { accept: ['night'], evidence: "which means they're active at night" },
    33: { accept: ['smell'], evidence: 'the kakapo has a very well-developed sense of smell' },
    34: { accept: ['scent'], evidence: 'each kakapo has its own distinctive scent' },
    35: { accept: ['booming'], evidence: 'produce a deep booming sound' },
    36: { accept: ['fruit'], evidence: 'produces a large quantity of fruit' },
    37: { accept: ['camouflage'], evidence: 'rely on its green feathers for camouflage' },
    38: { accept: ['stoats'], evidence: 'introduced mammals such as stoats, cats and rats' },
    39: { accept: ['islands'], evidence: 'to move every surviving bird to small offshore islands' },
    40: { accept: ['genome', 'genomes'], evidence: 'scientists have sequenced the genome of every living kakapo' },
  },
}
